### PR TITLE
Added an Adamantine Heavy SHield that might work.

### PR DESCRIPTION
**Pull request by vandervecken**
Can someone test this in combat?
Ref: https://github.com/kevL/TccScripts/issues/51

### CODE REVIEW

**Comment by vandervecken** [comment]
Added other shields too, and Masterwork shields, this works well.

**Comment by kevL** [comment]
if there's a duplicated resref in /Override, the engine just picks one.

if they're identical it's not a problem, but it's bad practice ofc. (one of them might change later, leading to an inconsistency)

> If that's an issue maybe we should push the regular adamantine shields to nwn2fixes and put the masterwork ones only in this mod?

y, iirc that's the policy we sorta established as precedent (with one of the crafting-related 2das, iirc). If a fix is required that doesn't *directly* impinge on the mechanics of TCCReboot, it goes in Nwn2Fixes ...

> And then perhaps we put int he Readme that folks should pair this mod with nwn2fixes too?

A note and/or link strikes me as a good thing, just be wary of "mission creep"

disclosure: I'm in the middle of doing a rather heavy modification to another codebase, so i've got umpteen variables and ambiguously interacting routines in my head. I'd like to bring that to a state of normalcy so I can look at shields with a clear head.

not sure when but it sounds like you got a good thing going,
/proceed pls

**Comment by vandervecken** [comment]
There's nothing left for you to do in TCC then. The shields - they work. I tested them. Please give me access to nwn2fixes to create a new branch (not merge powers if you don't want to, I can't figure out your documentation format there anyway) and I will put up a PR there too.

**Comment by kevL** [comment]
?
Can't you just fork it and make a PR ( the regular way )?

then i'd review it and add credits

(not sure if a new branch can be PR'd though -- no one's tried it that way -- tbh i don't see a pressing need for a new branch. Just add the UTIs in the appropriate folder ?)

**Comment by vandervecken** [comment]
I can definitely fork it, sure.

**Comment by vandervecken** [comment]
Created https://github.com/nwn2fixes/player/pull/30 from a fork.

**Pull request merged**
