### PR TITLE
Added Blacksmith recipes for Acid Bolt and Acid Bullet

### PR DESCRIPTION
**Pull request by vandervecken**
@kevL I had trouble testing this because in my crafting module for some reason giveItem isn't working with TCC templates, so I couldn't warp in the Bolt/Bullet molds (even though I could warp in other stuff).

Any idea why that might be?

### CODE REVIEW

**Comment by vandervecken** [comment]
Ref: https://github.com/kevL/TccScripts/issues/44

**Comment by vandervecken** [comment]
No typo. Something weird about my testing setup.

**Comment by kevL** [comment]
try compiling/running the script above. If the resrefs are/are not found by the engine on disk, idk, it might be a clue ...

**Comment by vandervecken** [comment]
It has been a long time but I am finally getting back into things. What do you recommend I use to compile your script?

More generally, I am having trouble using GiveItem on anything in the Templates folder in TCC. As I say, I think it has to do with my testing setup. I am using a particular module, and loading pre-saved games within it. The module I am using is the Crafting module, here:
https://neverwintervault.org/project/nwn2/module/craftingmod
Could the fact that I am running all my testing from within this mod be causing me these problems?

**Comment by kevL** [comment]
> Could the fact that I am running all my testing from within this mod be causing me these problems?

it shouldn't be... As long as the resrefs you're trying to create are in <player>/Override, the console commands are universal.

have you tried variations of "GiveItem" -- like "giveitem" -- ie, is the command working for other/stock blueprints?

re. script above
copy it into a textfile in <player>/Override, call it 'tcc_molds'

open the toolset (after the textfile has been created or it won't be found by the toolset)
File->OpenConversationOrScript...
compile.

then run the game, and

\`
debugmode 1
rs tcc_molds
debugmode 0
\`

note: "rs" stands for, and sometimes needs to be replaced by, "runscript" or "RunScript"

ps. double-check that something silly hasn't happened to
**My Documents/Neverwinter Nights 2/Override**
folder. (and that your working copy of TCCReboot is in there)

**Comment by vandervecken** [comment]
ok, I tried this. I got resref not found errors. Then I figured it out. But I don't have a fix.
So this is a new computer I have. Should be identical to the old computer, but apparently not.
* The tcc_molds script, when placed into C:\Users\mcohen\Documents\Neverwinter Nights 2\override, does run.
* The tcc_molds script, when placed into C:\Users\mcohen\Documents\Neverwinter Nights 2\override\TccScripts\Templates, does NOT run.
Something is wrong with the TccScripts folder. Then I realized I had downloaded it from within Linux-on-Windows using Git Clone. I deleted it and replaced it with a zip file downloaded from Github and put into place in Windows, and that worked.
But that's not a git repository.
Take 3, download by git cloning in Git Bash in Windows. It's a git repository, but tcc_molds won't run there either.
Something about whatever is there when it's a git repo is causing NWN to not accept it properly.
I don't know why this is, because it used to work fine on the old machine.
Lesson: Do not use git clone in LXSS to pull this thing down. It creates directories that behave weirdly in Windows.

**Comment by vandervecken** [comment]
Ok and it's working now. Git and NWN working.

**Comment by vandervecken** [comment]
Found a bug in Fire Bolts while completing testing.

**Comment by vandervecken** [comment]
Also switched out some readme stuff

**Pull request merged**
