### PR TITLE
Armor Level 4 Divine spells should use Earth essences (for armor) not…

### PR DESCRIPTION
**Pull request by vandervecken**
… Air essences (for weapons)

Resolves https://github.com/kevL/TccScripts/issues/4

I also took the liberty of making some of our text files encode in UTF-8 and Unix line endings. Notepad++ is grand, I'm doing this all on a Windows machine!

### CODE REVIEW

**Comment by kevL** [comment]
i merely browsed, but the changes to Crafting.2da look good.

I am however suspicious about exactly why switching to Unix-style line endings and encoding to UTF-8 results in git/github thinking that they are now binary files ...

**Comment by vandervecken** [comment]
Ok, so first off, you have it backwards unfortunately. These files were encoded in something that wasn't UTF-8 before. That's why they appeared as binaries. I made a text change to one of them and discovered that Git wouldn't give me diffs. Did some reading around and I think it was because of a lack of UTF-8 encoding, so I have moved them to UTF-8 so that they are no longer binaries. Unfortunately that means the diff in this commit is still binary, because the from-file is binary.

As for line endings. I am happy to reset to Windows style line endings if you wish for text files. I agree git defaults are best.

**Comment by kevL** [comment]
UTF-8 is great.

It's the ambiguity of line-endings that bother me. I suppose Git is going to store files with line endings however it does. I suggest however that in the Zip on the Vault, that textfiles use Windows-style EOLs since Nwn2 is basically a Windows only game.

here's the core of what bothers me -- Git should store textfiles exactly as they are commited. In fact it should store every file exactly as commited.

**Comment by vandervecken** [comment]
Anyway I switched bact to Windows line ends, so we should be good to go.

**Comment by kevL** [comment]
ok well toss it in and see what happens :^)

**Comment by kevL** [comment]
> but if it does that, every time I checkout and save a file in a different OS from the last guy, I generate a diff on every damn line.

that's what git config (should be) for ... imo.

**Pull request merged**
