### PR TITLE
Slaying recipes

### PR DESCRIPTION
**Pull request by vandervecken**
Add the Outsider recipe back into Slay Living.
Add missing Slay Living recipes to the Readmes

### CODE REVIEW

**Comment by vandervecken** [comment]
Removed an unnecessary UndeathToDeath recipe

**Comment by vandervecken** [comment]
@kevL my first significant recipe renumber

**Comment by vandervecken** [comment]
Looks like crafting.2da is being written out by YATA using spaces instead of tabs. Is that good or bad?

**Comment by kevL** [comment]
good. I've seen 2das reduced in size from 8mb to 2mb. I'm a big fan of the simplest that gets the job done solidly, and a single-space delimiter does that (plus the doc from Bioware says there shouldn't even be tabs in a 2da file).

Have you heard of the Player's Handbook for NwN2? it's (a) really neat, and (b) it comes with an app that rewrites the GUI-data it needs (in case a user wants the Handbook to reflect customized 2das) -- but the app borks out if there are tabs between the column headers ... that's a concrete example of space > tab

**Comment by kevL** [comment]
re. the Commit

let's try it out /shrug

**Comment by vandervecken** [comment]
Side question - I've seen a couple of NWN players handbook mods but I'm not sure which one is current.

**Comment by kevL** [comment]
https://neverwintervault.org/project/nwn2/other/gui/players-handbook-updated-version

**Pull request merged**
