### PR TITLE
Missing item construction

### PR DESCRIPTION
**Pull request by vandervecken**
Fixes https://github.com/kevL/TccScripts/issues/11

### CODE REVIEW

**Comment by kevL** [comment]
holy cr*p if you keep this up I'm going to use the actual TCCReboot 2da!

/good stuff \:)

**Comment by vandervecken** [comment]
Happy to. I want to power through the rest of them and release 2.05. If you have any more issues to add, please add them ASAP.
Also, please test my Adamantine Shield fix?

**Comment by kevL** [comment]
>Adamantine Shield fix?

will give it a try sometime today (hopefully)

Can #2 be closed (as long as its working, and any recipes that want to be changed can be dealt with in a case-by-case way) -- yer call

#7 doesn't appear to have an entirely satisfactory resolution due to engine-bug ... it strikes me as an issue of documentation ...

someday I'd like to do #19 but it's not a pressing issue for me atm

**Comment by vandervecken** [comment]
I *still* don't understand what's happening with #7. I know you tried to explain it to me. Use smaller words maybe? I was planning to look at it next.
I was planning to hit #2 and do all the recipes case by case this week.
I'm happy to follow your lead on #19.

So that means #7 and #2 are the only things left before we release 2.05!

**Comment by kevL** [comment]
re. #7 - https://github.com/kevL/TccScripts/issues/7#issuecomment-456545323

**Pull request merged**
